### ISSUE TITLE
Proper way to generate HTML outout

### ISSUE THREAD

**Issue by do3cc** [brechtm/citeproc-py#11]
I've tried to generate html output, following the examples, but I only get lists of strings with no meaning at all.
I'd like to understand, how to get html from the parser and how to modify the html formatter, so that each semantic element has some form of tag around it.

**Comment by jayvdb** [comment]
Adjusting the style to add semantic information is possible.

As a simple example, here I am using prefix and suffix to added a linked URL: https://github.com/jayvdb/pubpdf/blob/master/une/cell-une.csl#L121

Here is my 'generate a html publications list' code, in case it helps:
https://github.com/jayvdb/pubpdf/blob/master/pubpdf/_citeproc.py#L30

This issue can probably be closed.

**Comment by do3cc** [comment]
I don't have the possibility to test this any longer.
If you believe that your example is the solution, please do not hesitate to close this issue.
Thanks!
