### ISSUE TITLE
Tarball inconsistencies

### ISSUE THREAD

**Issue by danstender** [brechtm/citeproc-py#28]
The distributed tarballs of 0.3.0, the one at Pypi (e23da3b6c75485f82e1e5a725235731e) doesn't contain ``CHANGES.rst`` (not that big problem), but the one from Github (ccabf6bb628a598c3737aea5572b457e) misses ``citeproc/version.py``, which results in an installation break of  ``setup.py``.

**Comment by brechtm** [comment]
`CHANGES.rst` will now be included (1337c33). I forgot to include in the manifest. Thanks!

Are you talking about the archive that GitHub's "Download ZIP" produces which just takes a snapshot from the current HEAD? `citeproc/version.py` is generated when building distribution packages using `setup.py`, so no, that won't be included. I'd like to hide that "Download ZIP" button to avoid confusion, but I don't think that's possible.

**Comment by danstender** [comment]
No, I've mend ``https://github.com/brechtm/citeproc-py/archive/v0.3.0.tar.gz``, the one under ``releases/`` ...
```
$ ./setup.py 
Attempting to get version number from git...
fatal: Not a git repository (or any of the parent directories): .git
Assume we are running from a source distribution.
Traceback (most recent call last):
  File "./setup.py", line 36, in <module>
    with open(VERSION_FILE) as version_file:
IOError: [Errno 2] No such file or directory: 'citeproc/version.py'
```
Daniel

**Comment by brechtm** [comment]
Ah, found'm. Those are also automatically generated by GitHub when a new tag is pushed, so the same applies I'm afraid. They also include stuff like .gitignore and .gitmodules which shoudn't be part of a proper source release tarball. I could delete the release tarballs on GitHub, but I don't want to do that after each release.

**Comment by danstender** [comment]
All right, Pip's the place! :-)

BTW, a Debian package is coming up: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769159

Greetings,
Daniel Stender

**Comment by brechtm** [comment]
Installation instructions added in 4f2efda.
