### ISSUE TITLE
Decide on how to manage the CSL schema

### ISSUE THREAD

**Issue by brechtm** [brechtm/citeproc-py#29]
In commit cc9546c, I replaced the `citeproc/data/schema` directory with a submodule pointing to the upstream CSL schema repository. I forgot that this includes the CSL schema in RelaxNG **compact** format (rnc), and not in the XML format (rng) supported by lxml/libxml2, so these need conversion first.

Options:
1. Include the CSL schema in the citeproc-py repository as before.
2. Make the setup.py script check that the rng files are present. However, developers not running `setup.py` will also need the rng files to run `citeproc-test.py`.

**Comment by jayvdb** [comment]
I'd lean towards option 2, as option 1 opens the door for not keeping in sync with the CSL schema.

One recipe for working around this is to use `trang`, as the .travis.yml is doing.
https://github.com/brechtm/citeproc-py/commit/22d51a9462e340d17c38db42f098bba3cfea0747

`setup.py` could do that if the rng files are not present.
The generated rng file should be included in the pypi tarballs so that most users dont depend on `trang`.

**Comment by brechtm** [comment]
I was leaning towards option 1 myself. Motivation:
* option 2 requires contributors to install trang before they can run the tests (especially annoying in Windows due to the lack of a package manager)
* setyp.py is typically not run before starting development, so trang needs to be called manually
* we need to manually update the citeproc/data/schema submodule now and then anyway

**Comment by jayvdb** [comment]
As devils advocate only ... https://pypi.python.org/pypi/jingtrang looks like a nice way to handle the package management issue.  The tests could check the file exists, or that jingtrang exists, and bail out with a neat instruction to 'pip install jingtrang' if neither exist.

Unfortunately rnc2rng is completely unusable at present for CSL. https://github.com/djc/rnc2rng/issues/1
A quick look through the history indicates it has been making strides ahead recently, but it wouldnt be a quick project to get it handling CSL.

**Comment by jayvdb** [comment]
After a very large overhaul of rnc2rng for djc/rnc2rng#1, and my own small fix with https://github.com/djc/rnc2rng/pull/6 , the citeproc-py travis builds work without trang.
