### ISSUE TITLE
pages range

### ISSUE THREAD

**Issue by thorade** [brechtm/citeproc-py#32]
As discussed here
http://tex.stackexchange.com/q/58668/8569
the pages range should use -- (en-dash).
But not all .bib files follow this advice.
Currently, parsing fails if only a single hyphen is used.
Not sure if it makes sense to make parsing more stable or to require clean input.
If you go for the second option, a warning might be nice.

**Comment by brechtm** [comment]
This case was covered in 8161762. The next release will include it. No warning is output though.
