### ISSUE TITLE
pep8-naming

### ISSUE THREAD

**Issue by jayvdb** [brechtm/citeproc-py#41]
This package almost passes the rules for https://pypi.python.org/pypi/pep8-naming

The four violations are all in `model.py`

* `Date_Part`
* `Name_Part`
* `Et_Al`
* `Else_If`

If we fix those, backwards compatible names can be added so existing users dont break.

**Comment by brechtm** [comment]
These classes (and others in `model.py`) are automatically mapped to XML nodes in the CSL file (`date-part`, `name-part`, `et-al` and `else-if`). Having to choose between explicitly having to map those classes to XML node names and violating the naming rules, I prefer the latter.
