### ISSUE TITLE
Strange bug in Python 2.7

### ISSUE THREAD

**Issue by jayvdb** [brechtm/citeproc-py#48]
The travis build of 5289f6ae2c resulted in Python 2.7 job failing: https://travis-ci.org/brechtm/citeproc-py/builds/100241495 .

This also happened on my sync build of the same commit, and now a PR has the same problem.

The previous build was for a few commits earlier, so it looks like a few commits were pushed at the same time to github as a series.

It looks like ac27de4cea is the cause of the build breakage.

**Comment by brechtm** [comment]
Yes, I know what the cause is. I will commit a fix later today.
