### ISSUE TITLE
csl test suite has moved to github

### ISSUE THREAD

**Issue by jayvdb** [brechtm/citeproc-py#62]
The bitbucket repo for the test suite has been moved to
https://github.com/citation-style-language/test-suite

See
https://github.com/brechtm/citeproc-py/blob/master/tests/citeproc-test.py#L23 and friends.

**Comment by brechtm** [comment]
The citeproc-test script now clones the new test suite repository. However, we might want to simply use a git submodule (like for the locales and schema). I suppose the script can still check whether the clone is up to date or not and output a message if it's not.

**Comment by yarikoptic** [comment]
or use git-subtree (see e.g. https://www.atlassian.com/git/tutorials/git-subtree for introduction).
In any case, original issue was addressed, so I will close it (please reopen if htat is not desired)
