### ISSUE TITLE
Unsupported BibTeX fields

### ISSUE THREAD

**Issue by guillermomarco** [brechtm/citeproc-py#68]
I'm new to citeproc and trying to build bibliography from a *.bib file. However I'm experiencing that a lot of fields aren't supported. I've tried updating my libs, even installed citeproc-py from github to get some possible fixes.

```
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'primaryclass'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'arxivid'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'doi'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'eprint'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'pmid'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'archiveprefix'
  warn("Unsupported BibTeX field '{}'".format(field))
/usr/local/lib/python2.7/dist-packages/citeproc/source/bibtex/bibtex.py:90: UserWarning: Unsupported BibTeX field 'abstract'
  warn("Unsupported BibTeX field '{}'".format(field))
```

Example bib file I'm trying to read:

> @article{Trapnell2009,
> abstract = {MOTIVATION: A new protocol for sequencing the messenger RNA in a cell, known as RNA-Seq, generates millions of short sequence fragments in a single run. These fragments, or 'reads', can be used to measure levels of gene expression and to identify novel splice variants of genes. However, current software for aligning RNA-Seq data to a genome relies on known splice junctions and cannot identify novel ones. TopHat is an efficient read-mapping algorithm designed to align reads from an RNA-Seq experiment to a reference genome without relying on known splice sites.$\backslash$n$\backslash$nRESULTS: We mapped the RNA-Seq reads from a recent mammalian RNA-Seq experiment and recovered more than 72{\%} of the splice junctions reported by the annotation-based software from that study, along with nearly 20,000 previously unreported junctions. The TopHat pipeline is much faster than previous systems, mapping nearly 2.2 million reads per CPU hour, which is sufficient to process an entire RNA-Seq experiment in less than a day on a standard desktop computer. We describe several challenges unique to ab initio splice site discovery from RNA-Seq reads that will require further algorithm development.$\backslash$n$\backslash$nAVAILABILITY: TopHat is free, open-source software available from http://tophat.cbcb.umd.edu.$\backslash$n$\backslash$nSUPPLEMENTARY INFORMATION: Supplementary data are available at Bioinformatics online.},
> archivePrefix = {arXiv},
> arxivId = {cs/9605103},
> author = {Trapnell, Cole and Pachter, Lior and Salzberg, Steven L.},
> doi = {10.1093/bioinformatics/btp120},
> eprint = {9605103},
> isbn = {1367-4811 (Electronic)$\backslash$r1367-4803 (Linking)},
> issn = {13674803},
> journal = {Bioinformatics},
> number = {9},
> pages = {1105--1111},
> pmid = {19289445},
> primaryClass = {cs},
> title = {{TopHat: Discovering splice junctions with RNA-Seq}},
> volume = {25},
> year = {2009}
> }

**Comment by brechtm** [comment]
These are fields that are not supported by BibTeX and/or which citeproc does not know how to map to CSL fields. The problem with BibTeX is that there's only a very limited set of officially supported fields. Many other are added ad-hoc.

Are any of those fields included in the citations or bibliography? If not, there is nothing to worry about. Otherwise, you can [add mappings](https://github.com/brechtm/citeproc-py/blob/master/citeproc/source/bibtex/bibtex.py#L21) for these and create a pull request.

Some of the fields in your BibTeX file that can be easily mapped to CSL:

- `abstract` to `abstract`
- `doi` to `DOI`
- `pmid` to `PMID`

These seem general enough to be included.

**Comment by guillermomarco** [comment]
Check #70
