### ISSUE TITLE
Please release 0.3.1 or 0.4.0

### ISSUE THREAD

**Issue by yarikoptic** [brechtm/citeproc-py#72]
There was a reasonable number of fixes introduced since 0.3.0 (just ran into pages parsing in bibtex fixed in 816176285daf58aaaa57fbfbb1b601d5aa8d6336). Given that the last release (0.3.0) was almost 2 years ago, it would be awesome if new, at least a bugfix, release was cut

thanks in advance!

**Comment by yarikoptic** [comment]
oh, and apparently allowing encoding being passed into BibTeX reader/parser was fixed after.... please please please ;)

**Comment by brechtm** [comment]
I'm currently working on a rinohtype release. I'll try to make a citeproc-py release once that's done.

In the meantime, you're always welcome to help maintain citeproc-py if you feel up to it (handle bugs, process pull requests and make releases). At this moment, I'm not a user of citeproc-py myself, so I hope you understand it's not high on my priority list.

**Comment by yarikoptic** [comment]
I can try helping out, but can't promise much of heavy activity.  
I could promise though facilitating timely uploads of new releases to Debian and possibly provide backport builds from neurodebian

**Comment by jayvdb** [comment]
fwiw, next week I will throw a week or so at this project.  I can do a pypi release then.

**Comment by jayvdb** [comment]
By merging a few of the easy PRs, I think there is more than enough to justify calling the next release 0.4.0

**Comment by brechtm** [comment]
@yarikoptic I've added you as a collaborator to the citeptoc-py repository, just in case.

Thanks @jayvdb. Good timing! :-)

Tagging the release 0.3.1 or 0.4.0 should be based on the fact whether changes have been made to the API or not (ref [semver.org](semver.org)):

> Consider a version format of X.Y.Z (Major.Minor.Patch). Bug fixes not affecting the API increment the patch version, backwards compatible API additions/changes increment the minor version, and backwards incompatible API changes increment the major version.

**Comment by yarikoptic** [comment]
On Mon, 18 Jul 2016, John Vandenberg wrote:

>    fwiw, next week I will throw a week or so at this project. I can do a pypi
>    release then.

yeay -- great, and thanks in advance!

**Comment by jayvdb** [comment]
@brechtm , the changes which I feel warrant a minor version bump are mapping more fields from the BibTeX to the CSL data.  IMO adding fields that were not previously supported is a minor release, as that will cause information which was previously discarded to now appear in the output.  It isnt even strictly backwards compatible, as the same input will create a different output, but the input format is a fairly mature & stable and reasonably specified format so it is a bug that earlier versions discard parts of the input.  But people rely on such bugs after a while .. ;-)

**Comment by brechtm** [comment]
Sure. I would just like to follow Semantic Versioning guidelines as closely as possible. While I don't think that technically is an API change, semver does say this:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. **It MAY be incremented if substantial new functionality or improvements are introduced within the private code**. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

Since there have indeed been quite a lot of changes since 0.3.0, I'd say 0.4.0 would indeed be a good choice.

While reading the Semantic Versioning text, I was reminded that major version 0 is special:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

I guess we shouldn't wait too long to move to 1.0.0, as the API is in fact already pretty stable. Perhaps not the upcoming release, but the one following it. Or should we wait till CSL 1.0.1 is more fully implemented first?

**Comment by jayvdb** [comment]
IMO `1.0` means it implements a well defined goal. If not all of CSL 1.0.1, the parts omitted should be clearly described, and excluded based on sensible/rational reasons as opposed to "not done yet".  e.g. they are only used by a distinct cohort of users.

IMO, one goal is 'doesnt crash for the test suite' ;-)  I would put that at about `0.5`.

Passing the majority of the test suite should be high on the agenda, and would be about `0.8`, allowing a little room for bug fixes and minor rewrites before `1.0`

**Comment by yarikoptic** [comment]
so how about 0.4? ;)

**Comment by yarikoptic** [comment]
@brechtm  still would be very interested in a release of some kind since we keep running into the issues while trying to use citeproc within duecredit project

**Comment by brechtm** [comment]
Sorry this took so long. 0.4.0 is now available from [PyPI](https://pypi.python.org/pypi/citeproc-py/0.4.0). Let me know if you run into any problems.

**Comment by yarikoptic** [comment]
woohoo -- thank you!
