### ISSUE TITLE
Please release 0.4.1

### ISSUE THREAD

**Issue by yarikoptic** [brechtm/citeproc-py#79]
As people run into what has been fixed since 0.4.0 (e.g. #78 )

**Comment by yarikoptic** [comment]
Please!  At least kicking out release to pypi should be not very time consuming (unless some tests etc started to fail since last time). If interested, I could try to help with that. My login is the same on pypi

Cheers

**Comment by yarikoptic** [comment]
I Didn't yet check if I got super powers on pypi, bit I will try to cook up changelog entries today and kick our release on GitHub

**Comment by yarikoptic** [comment]
I Didn't yet check if I got super powers on pypi, bit I will try to cook up changelog entries today and kick our release on GitHub

**Comment by brechtm** [comment]
Thanks, @yarikoptic. I just added you as a maintainer at PyPi!

**Comment by yarikoptic** [comment]
Awesome, thank you!

**Comment by yarikoptic** [comment]
Ok, have done it as 0.5.0 since number of changes is large, and some older pythons were dropped and new added.  uploaded to pypi as well.
