### ISSUE TITLE
Support for languages other than English

### ISSUE THREAD

**Issue by jsmm** [brechtm/citeproc-py#80]
As far as I can tell, citeproc-py doesn't support to set the language as metadata, such as `-M lang:es`. This is a very useful argument in pandoc-citeproc to render biblographies in other languages. Is this correct?

**Comment by brechtm** [comment]
You can pass a locale specification to `CitationStylesStyle`. For example:

    bib_style = CitationStylesStyle('harvard1', locale='en-US', validate=False)

**Comment by jsmm** [comment]
Thanks for your reply. Still no luck when I include `locale` in the config of python Nikola with pandoc and citeproc-py. This is part of the error message:

```
pandoc: unrecognized option `--locale=en-US'
unrecognized option `--validate=False'
Try pandoc --help for more information.
TaskError - taskid:render_posts:cache/posts/test-de-pandoc.html
PythonAction Error
```
The config (that works without the `locale` argument I need) is:
```
PANDOC_OPTIONS = [
    '--filter=pandoc-citeproc', '--bibliography=./data/biblio-books.bib',
    '--csl=./data/turabian-fullnote-bibliography.csl', '--locale=en-En',
    '--validate=False', '--base-header-level=2']
```

**Comment by brechtm** [comment]
I'm not familiar with Nikola, but as far as I can see, it doesn't use citeproc-py! Neither does pandoc. So I'm not sure how you ended up here. Unless citeproc-py is somehow involved, I don't think I will be able to help you. Please ask for help in pandoc or Nikola channels.

**Comment by jsmm** [comment]
That may very well be so. Thanks for your attention.

**Comment by brechtm** [comment]
No problem. Cheers!
