### ISSUE TITLE
Name clash with Python types module

### ISSUE THREAD

**Issue by mskoh52** [brechtm/citeproc-py#82]
The `types` module from Python3 clashes with the `types.py` file here. This can cause issues, in particular when using emacs flycheck integration. Maybe a minor inconvenience, but it's also a pretty minor fix. Just rename everything here from `types` to `csltypes` for example.

**Comment by yarikoptic** [comment]
with relative imports ambiguity against stock modules is resolved.  I do not think Python can and/or should limit names of modules internal to package.  Hence there is `types` and `string`, could be `io` etc.  If you are still encountering this issue, better check with `flycheck` to take care about smarter analysis of what it is looking at.  Feel free to reopen if I am wrong and missing the issue.
